HQP: cg_sfun.h File Reference
cg_sfun.h File Reference
Native S-function code generation include file for Hqp.
Macros
#define HXI_STRINGIFY(token) #token
Functions
void Hxi_SimStruct_init (SimStruct *S)
Entry function into Hxi S-function.
Detailed Description
Native S-function code generation include file for Hqp.
Currently macros for checking optional S-function methods are defined. This allows to write the same code for an inlined S-function and for an external MEX S-function.
(Simulink is a registered trademark of The MathWorks, Inc.)
rf, 05/05/2001
Function Documentation
void Hxi_SimStruct_init (SimStruct * S)
Entry function into Hxi S-function.
It initializes a SimStruct with S-function name, version, and with pointers to S-function methods.
References mdlDerivatives(), mdlInitializeConditions(), mdlInitializeSampleTimes(), mdlInitializeSizes(), mdlJacobian(), mdlOutputs(), mdlStart(), mdlTerminate(), and mdlUpdate().