HQP: Hqp_DocpSpec Class Reference
Hqp_DocpSpec Class Reference
Hold pointers to functions provided by an application using HQP.
#include <Hqp.h>
Public Member Functions
Hqp_DocpSpec ()
Constructor initializes all pointers with NULL.
Public Attributes
void(* setup_horizon)(void *clientdata, int &k0, int &kf)
Obligatory: setup discrete control horizon.
void(* setup_vars)(void *clientdata, int k, VECP x, VECP x_min, VECP x_max, IVECP x_int, VECP u, VECP u_min, VECP u_max, IVECP u_int, VECP c, VECP c_min, VECP c_max)
Obligatory: setup variables per control interval.
void(* setup_struct)(void *clientdata, int k, const VECP x, const VECP u, MATP fx, MATP fu, IVECP f_lin, VECP f0x, VECP f0u, int &f0_lin, MATP cx, MATP cu, IVECP c_lin, MATP Lxx, MATP Luu, MATP Lxu)
Optional: setup sparse structure and mark linear constraints per control interval.
void(* init_simulation)(void *clientdata, int k, VECP x, VECP u)
Optional: initialize variables via initial-value simulation.
void(* update_vals)(void *clientdata, int k, const VECP x, const VECP u, VECP f, Real &f0, VECP c)
Obligatory: update objective and constraints per control interval.
void(* update_stage)(void *clientdata, int k, const VECP x, const VECP u, VECP f, Real &f0, VECP c, MATP fx, MATP fu, VECP f0x, VECP f0u, MATP cx, MATP cu, const VECP rf, const VECP rc, MATP Lxx, MATP Luu, MATP Lxu)
Optional: update objective, constraints and derivatives per control interval.
Detailed Description
Hold pointers to functions provided by an application using HQP.
Constructor & Destructor Documentation
Hqp_DocpSpec::Hqp_DocpSpec () inline
Constructor initializes all pointers with NULL.
References init_simulation, setup_horizon, setup_struct, setup_vars, update_stage, and update_vals.
Member Data Documentation
void(* Hqp_DocpSpec::init_simulation)(void *clientdata, int k, VECP x, VECP u)
Optional: initialize variables via initial-value simulation.
Referenced by Hqp_DocpSpec().
void(* Hqp_DocpSpec::setup_horizon)(void *clientdata, int &k0, int &kf)
Obligatory: setup discrete control horizon.
Referenced by Hqp_DocpSpec().
void(* Hqp_DocpSpec::setup_struct)(void *clientdata, int k, const VECP x, const VECP u, MATP fx, MATP fu, IVECP f_lin, VECP f0x, VECP f0u, int &f0_lin, MATP cx, MATP cu, IVECP c_lin, MATP Lxx, MATP Luu, MATP Lxu)
Optional: setup sparse structure and mark linear constraints per control interval.
Referenced by Hqp_DocpSpec().
void(* Hqp_DocpSpec::setup_vars)(void *clientdata, int k, VECP x, VECP x_min, VECP x_max, IVECP x_int, VECP u, VECP u_min, VECP u_max, IVECP u_int, VECP c, VECP c_min, VECP c_max)
Obligatory: setup variables per control interval.
Referenced by Hqp_DocpSpec().
void(* Hqp_DocpSpec::update_stage)(void *clientdata, int k, const VECP x, const VECP u, VECP f, Real &f0, VECP c, MATP fx, MATP fu, VECP f0x, VECP f0u, MATP cx, MATP cu, const VECP rf, const VECP rc, MATP Lxx, MATP Luu, MATP Lxu)
Optional: update objective, constraints and derivatives per control interval.
Referenced by Hqp_DocpSpec().
void(* Hqp_DocpSpec::update_vals)(void *clientdata, int k, const VECP x, const VECP u, VECP f, Real &f0, VECP c)
Obligatory: update objective and constraints per control interval.
Referenced by Hqp_DocpSpec().
The documentation for this class was generated from the following file:
Hqp.h