HQP: Hxi_SFunction.h File Reference
Hxi_SFunction.h File Reference
Interface to a Simulink(R) S-function given as binary object.
#include "Hxi_SimStruct.h"
Functions
Supported S-function methods.
Avoid multiple inclusion
void mdlInitializeSizes (SimStruct *S)
Initialize sizes of data vectors in SimStruct.
void mdlStart (SimStruct *S)
Optional: Allocate local ressources for simulation.
void mdlInitializeSampleTimes (SimStruct *S)
Initialize sample times.
void mdlInitializeConditions (SimStruct *S)
Optional: Compute initial conditions.
void mdlOutputs (SimStruct *S, int_T tid)
Compute model outputs.
void mdlUpdate (SimStruct *S, int_T tid)
Optional: Update discrete-time states.
void mdlDerivatives (SimStruct *S)
Optional: Compute derivatives for continuous-time states.
void mdlJacobian (SimStruct *S)
Optional: Compute Jacobian J = d(dxc,xd,y)/d(xc,xd,u).
void mdlTerminate (SimStruct *S)
Release resources allocated for simulation.
Detailed Description
Interface to a Simulink(R) S-function given as binary object.
Several S-function methods are supported that redirect the call to the binary object. Data is communicated through a SimStruct.
(Simulink is a registered trademark of The MathWorks, Inc.)
rf, 01/07/2005
Function Documentation
void mdlDerivatives (SimStruct * S) inline
Optional: Compute derivatives for continuous-time states.
References Hxi_mdlDerivatives().
Referenced by Hxi_SimStruct_init().
void mdlInitializeConditions (SimStruct * S) inline
Optional: Compute initial conditions.
References Hxi_mdlInitializeConditions().
Referenced by Hxi_SimStruct_init().
void mdlInitializeSampleTimes (SimStruct * S) inline
Initialize sample times.
References Hxi_mdlInitializeSampleTimes().
Referenced by Hxi_SimStruct_init().
void mdlInitializeSizes (SimStruct * S) inline
Initialize sizes of data vectors in SimStruct.
This function works with the shared object found under ssGetPath(S), calls the S-function method mdlInitializeSizes and allocates memory required for a level 2 S-function. The model parameters must have been initialized prior to calling this function.
References Hxi_mdlInitializeSizes().
Referenced by Hxi_SimStruct_init().
void mdlJacobian (SimStruct * S) inline
Optional: Compute Jacobian J = d(dxc,xd,y)/d(xc,xd,u).
References Hxi_mdlJacobian().
Referenced by Hxi_SimStruct_init().
void mdlOutputs (SimStruct * S, int_T tid) inline
Compute model outputs.
References Hxi_mdlOutputs().
Referenced by Hxi_SimStruct_init().
void mdlStart (SimStruct * S) inline
Optional: Allocate local ressources for simulation.
References Hxi_mdlStart().
Referenced by Hxi_SimStruct_init().
void mdlTerminate (SimStruct * S) inline
Release resources allocated for simulation.
References Hxi_mdlTerminate().
Referenced by Hxi_SimStruct_init().
void mdlUpdate (SimStruct * S, int_T tid) inline
Optional: Update discrete-time states.
References Hxi_mdlUpdate().
Referenced by Hxi_SimStruct_init().